# Site settings
baseurl = "https://www.automationstation.com.au"
languageCode = "en-us"
title = "Automation Station"
theme = "agency"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-131820474-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Automation Station"
  description = "Document automation services for law firms, in-house legal teams and other businesses requiring high-quality, consistent documents."
  email = "contact@automationstation.com.au"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "[Go home](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Automation Station"
    # Optional logo as brand stored in img/
    logo = "logo.jpg"
    services = "Services"
    portfolio = "Showcase"
    about = "About"
    team = "Team"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # [[menu.prepend]]
     # url = "http://gohugo.io"
     # name = "Hugo"
     # weight = 10

    # postpended links
    # [[menu.postpend]]
     # url = "http://gohugo.io"
     # name = "External link"
     # weight = 10

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in the 'static/img' folder.
    title = "Welcome to Automation Station!"
    subtitle = "Making professional document automation available to everyone."
    buttonText = "Tell me more"

  # Services section
  [params.services]
    enable = true
    title = "Services"
    subtitle = "Everything you need to make your document automation project a success. We specialise in automating legal documents for law firms, in-house legal teams and other businesses requiring high-quality, consistent documents."
    # subtitle = "No matter where you are on your automation journey, we can help."

    [[params.services.row]]

    [[params.services.row.list]]
      # icon = "fas fa-connectdevelop"
      # icon = "fas fa-code"
      icon = "fas fa-window-restore"
      title = "Platform"
      description = "Too many automation platform choices? Don't want another system to set up and manage?<br>We can help!"
      url = "/services/platform"

    [[params.services.row.list]]
      icon = "fas fa-file-code"
      title = "Automation"
      description = "Wishing that your document template would code itself? Want to build better forms?<br>We can help!"
      url = "services/automation"

    [[params.services.row.list]]
      icon = "fas fa-pen"
      title = "Content"
      description = "Not so sure about that wording? Need better legal content? We have connections...<br>(who can help!)"
      url = "services/content"

  # Portfolio section
  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Showcase"
    subtitle = "Projects we've helped implement."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "About us"
    subtitle = "Our mission is to make professional document automation available to everyone."
    #endpoint = "Be part<br>of our<br>story!"

  # Team section
  [params.team]
    enable = false
    # Possibility to center items
    #center = true
    title = "Our amazing team"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    description = "Teams description."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "1.jpg"
      name = "Kay Garland"
      position = "Lead Designer"
      reportsTo = "CTO"
      livesIn = "[Munich, Germany](#some-maps-url)"
      scope = [
        "UX for [member dashboard](#)",
        "Maintainer for [awesome-project](#)",
        "Open Source [community management](#)"
      ]
      # For bio markdown and even multiline strings are available.
      bio = """Kay is an awesome Lead Designer with heaps of experience in the field of UX.
She worked at Pied Piper for years until they went belly up."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Larry Parker"
      position = "Lead Marketer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "3.jpg"
      name = "Diana Pertersen"
      position = "Lead Developer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = ""

  # Footer section
  [params.footer]
    enable = true
    copyright = "Automation Station Pty Ltd (ABN 65 630 299 197)"

    # [[params.footer.social]]
     # icon = "far fa-twitter"
     # link = "#"
     # title = "Twitter"

    [[params.footer.social]]
      icon = "fab fa-facebook"
      link = "https://www.facebook.com/AutomationStation.com.au"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fab fa-linkedin"
      link = "https://www.linkedin.com/company/automationstation/"
      title = "LinkedIn"

    [[params.footer.quicklinks]]
      icon = "fas fa-fingerprint"
      text = "Privacy Policy"
      link = "/legal/privacy"

    [[params.footer.quicklinks]]
      icon = "fas fa-book"
      text = "Terms of Use"
      link = "/legal/terms"