# Site settings
baseurl = "https://amazing-snyder-22e93d.netlify.com/"
languageCode = "en-us"
title = "Automation Station"
theme = "agency"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-131820474-1"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Automation Station"
  description = "Document automation services for law firms, in-house legal teams and other businesses requiring high-quality, consistent documents."
  email = "contact@automationstation.com.au"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "[Go home](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Automation Station"
    # Optional logo as brand stored in img/
    logo = "logo.jpg"
    services = "Services"
    portfolio = "Showcase"
    about = "About"
    team = "Team"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # [[menu.prepend]]
     # url = "http://gohugo.io"
     # name = "Hugo"
     # weight = 10

    # postpended links
    # [[menu.postpend]]
     # url = "http://gohugo.io"
     # name = "External link"
     # weight = 10

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in the 'static/img' folder.
    title = "Welcome to Automation Station!"
    subtitle = "Making professional document automation available to everyone."
    buttonText = "Tell me more"

  # Services section
  [params.services]
    enable = true
    title = "Services"
    subtitle = "Everything you need to make your document automation project a success."
    # subtitle = "No matter where you are on your automation journey, we can help."

    [[params.services.row]]

    [[params.services.row.list]]
      # icon = "fas fa-connectdevelop"
      # icon = "fas fa-code"
      icon = "fas fa-window-restore"
      title = "Platform"
      description = "Puzzled by too many automation platform options? Reluctant to set up and manage yet another system? We can help!"
      url = "/services/platform"

    [[params.services.row.list]]
      icon = "fas fa-file-code"
      title = "Automation"
      description = "Wishing that your document template would hurry up and code itself? Want to build better forms? We can help!"
      url = "services/automation"

    [[params.services.row.list]]
      icon = "fas fa-pen"
      title = "Content"
      description = "Not so sure about that wording? Need better legal content? We have connections (who can help!)"
      url = "services/content"

# These are from when Automation Station was going to focus on automation more generally (e.g. workflow automation), rather than document automation only.
    # [[params.services.row.list]]
     # icon = "fas fa-file-alt"
     # title = "Document automation"
     # description = "From recommending a document automation platform and managing it for you, to automating just one document  a document for a one-off project."
     # url = "#"

    # [[params.services.row.list]]
     # icon = "far fa-sitemap"
     # title = "Workflow automation"
     # description = "Automation is more than documents. Get approval steps and other workflows integrated right into  systems."
     # url = "#"

    # [[params.services.row.list]]
     # icon = "fas fa-sync-alt"
     # title = "Continuous improvement"
     # description = "Automation is more than doing the same things more efficiently. Once automated, we can help you keep making the system better and better!"
     # url = "#" 

  # Portfolio section
  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Showcase"
    subtitle = "Projects we've helped implement."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "About us"
    subtitle = "We make developing high-quality automated legal documents accessible to everyone."
    #endpoint = "Be part<br>of our<br>story!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    #[[params.about.events]]
     # img = "1.jpg"
     # date = "2018"
     # title = "Looking ahead"
     # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    #[[params.about.events]]
     # img = "2.jpg"
     # date = "January 2019"
     # title = "Automation Station is born"
     # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

    #[[params.about.events]]
     # img = "3.jpg"
     # date = "The next 5 to 10 years"
     # title = "Our Humble Beginnings"
     # description = "We believe that over this timeframe, the majority of law firms and in-house legal departments will use automation to produce their legal documents."

    #[[params.about.events]]
     # img = "4.jpg"
     # date = "July 2014"
     # title = "Phase Two Expansion"
     # description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


  # Team section
  [params.team]
    enable = false
    # Possibility to center items
    #center = true
    title = "Our amazing team"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    description = "Teams description."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "1.jpg"
      name = "Kay Garland"
      position = "Lead Designer"
      reportsTo = "CTO"
      livesIn = "[Munich, Germany](#some-maps-url)"
      scope = [
        "UX for [member dashboard](#)",
        "Maintainer for [awesome-project](#)",
        "Open Source [community management](#)"
      ]
      # For bio markdown and even multiline strings are available.
      bio = """Kay is an awesome Lead Designer with heaps of experience in the field of UX.
She worked at Pied Piper for years until they went belly up."""
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Larry Parker"
      position = "Lead Marketer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "3.jpg"
      name = "Diana Pertersen"
      position = "Lead Developer"
      social = [
        ["fa-twitter", "#"],
        ["fa-facebook", "#"],
        ["fa-linkedin", "#"]
      ]

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "Lorem ipsum dolor sit amet consectetur."
    # buttonText = "Send message"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    # email = "your@email.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    # [params.contact.form.name]
     # text = "Your Name *"
     # warning = "Please enter your name."

    # [params.contact.form.email]
     # text = "Your Email *"
     # warning = "Please enter your email address."

    # [params.contact.form.phone]
     # text = "Your Phone *"
     # warning = "Please enter your phone number."

    # [params.contact.form.message]
     # text = "Your Message *"
     # warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Automation Station"

    # [[params.footer.social]]
     # icon = "far fa-twitter"
     # link = "#"
     # title = "Twitter"

    [[params.footer.social]]
      icon = "fab fa-facebook"
      link = "https://www.facebook.com/AutomationStation.com.au"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fab fa-linkedin"
      link = "https://www.linkedin.com/company/automationstation/"
      title = "LinkedIn"

    [[params.footer.quicklinks]]
      icon = "fas fa-fingerprint"
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      icon = "fas fa-book"
      text = "Terms of Use"
      link = "#"